### ISSUE TITLE
Missing Spark 1.5.1 / Hadoop 1 binary

### ISSUE THREAD

**Issue by jcainey** [amplab/spark-ec2#15]
Prior to Spark 1.5.1 there has been a pre-built version of Spark, packaged with Hadoop 1, stored in http://s3.amazonaws.com/spark-related-packages - e.g. for Spark 1.5.0 we had `spark-1.5.0-bin-hadoop1.tgz`. However this seems to no longer be the case. I'm not sure if this is an accidental omission or whether it reflects a change in policy, although I suspect the former since the Scala 2.11 version  `spark-1.5.1-bin-hadoop1-scala2.11.tgz` exists.

Either way, since Hadoop 1 is the default, it would be good if there was a warning or some kind of documentation that gave a hint in this direction - otherwise you have to keep a very close eye on the setup script to notice the 404.

**Comment by JoshRosen** [comment]
This is accidental. I'm working on fixing this as we speak but am currently blocked by some infra outages. Please follow the [Spark 1.5.1 - Scala 2.10 - Hadoop 1 package is missing from S3](http://apache-spark-developers-list.1001551.n3.nabble.com/Spark-1-5-1-Scala-2-10-Hadoop-1-package-is-missing-from-S3-td14446.html) thread on the Spark developers mailing list for updates.
