### ISSUE TITLE
Submission scripts are broken on ec2 clusters started with spark-ec2 with private IP's

### ISSUE THREAD

**Issue by mdagost** [amplab/spark-ec2#2]
See [this issue in JIRA](https://issues.apache.org/jira/browse/SPARK-9884).  Fix coming shortly.  @tkunicki

**Comment by tkunicki** [comment]
The referenced patch was implemented to resolve an issue with EC2 VPC clusters and broken links in the web ui.   When a public DNS names wasn't present, the web UI links were generated w/o hostnames.  The private IP address is used as a stand-in in this case so that machines on the VPC (e.g. connected via VPN) can utilize the web UI w/ private IPs.

**Comment by mdagost** [comment]
Yep.  That makes total sense (that's actually the mode in which we run our clusters).  Were you able to submit with that change?  I don't entirely understand what the deal is, but this simple change unbreaks everything, which is what I'm going to put in my PR.  The first command fails without the `export`.

```
export SPARK_PUBLIC_DNS=`wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname`
if [[ -z "$SPARK_PUBLIC_DNS" ]]; then
    export SPARK_PUBLIC_DNS=`wget -q -O - http://169.254.169.254/latest/meta-data/local-ipv4`
fi
```

**Comment by tkunicki** [comment]
I didn't have an issue w/ spark-ec2 generated clusters running 1.3.[01] using amazon linux (custom w/ java 8).  huh, I don't understand the functional difference between the `export` positions.

**Comment by mdagost** [comment]
Yeah, it's weird.  I don't understand the difference either, but it seems to have something to do with the effect of calling multiple bash scripts from each other using `source`, as far as I can tell.  But it's definitely that first line that's causing the problem (none of the submission scripts make it past that line), and this definitely fixes it while correctly setting the `SPARK_PUBLIC_DNS`.

BTW, I'm just using whatever the default AMI is for 1.4.1.

**Comment by tkunicki** [comment]
@mdagost, strange question, is `wget` installed on your system?  what does it return on your VPC instance when run from the shell with the script commands?  Just trying to make sense of your fix.  Is there some behavior with `export=`  with executed commands when the return code is non-zero?

**Comment by mdagost** [comment]
Yep--wget is installed (it's the regular official spark ami that I'm using). From a shell, it does what you'd expect it to do. The only thing I can think of is that that script is being sourced several layers deep when you call the suit script. I also thought about the return code issue but couldn't dig anything up.  Could be that something with the back ticks too. 

Are you able to start a 1.4.1 cluster with the spark-ec2 to verify?  Just a single node on a private VPC with all the defaults will do it.  I know this seems very strange, but I swear I'm not crazy :)

Michelangelo

**Comment by mdagost** [comment]
Actually, it's possible that it's related to the non-zero exit code and this:

http://unix.stackexchange.com/questions/23026/how-can-i-get-bash-to-exit-on-backtick-failure-in-a-similar-way-to-pipefail
