### ISSUE TITLE
Errors when deploying spark on EC2 with specified AMI-ID

### ISSUE THREAD

**Issue by yj-yjh-yj** [amplab/spark-ec2#27]
Hi guys,

I was just trying to deploy spark on EC2 with the following commands:

/spark-ec2 --key-pair=key_spark_oregon --identity-file=key_spark_oregon.pem -a ami-9abea4fb --instance-type=t2.micro --region=us-west-2 --zone=us-west-2a launch my-spark-cluster

So I used an AMI "ami-9abea4fb" here, which is a Ubuntu HVM, then I got the following information:

Setting up security groups...
Searching for existing cluster my-spark-cluster in region us-west-2...
Launching instances...
Launched 1 slave in us-west-2a, regid = r-10c232c9
Launched master in us-west-2a, regid = r-11c232c8
Waiting for AWS to propagate instance metadata...
Waiting for cluster to enter 'ssh-ready' state.........
Cluster is now in 'ssh-ready' state. Waited 213 seconds.
Generating cluster's SSH key on master...
Warning: Permanently added 'ec2-52-39-228-214.us-west-2.compute.amazonaws.com,52.39.228.214' (ECDSA) to the list of known hosts.
Please login as the user "ubuntu" rather than the user "root".

Connection to ec2-52-39-228-214.us-west-2.compute.amazonaws.com closed.
Warning: Permanently added 'ec2-52-39-228-214.us-west-2.compute.amazonaws.com,52.39.228.214' (ECDSA) to the list of known hosts.
Transferring cluster's SSH key to slaves...
ec2-52-39-221-224.us-west-2.compute.amazonaws.com
Warning: Permanently added 'ec2-52-39-221-224.us-west-2.compute.amazonaws.com,52.39.221.224' (ECDSA) to the list of known hosts.
Please login as the user "ubuntu" rather than the user "root".

Cloning spark-ec2 scripts from https://github.com/amplab/spark-ec2/tree/branch-1.5 on master...
Warning: Permanently added 'ec2-52-39-228-214.us-west-2.compute.amazonaws.com,52.39.228.214' (ECDSA) to the list of known hosts.
Please login as the user "ubuntu" rather than the user "root".

Connection to ec2-52-39-228-214.us-west-2.compute.amazonaws.com closed.
Deploying files to master...
Warning: Permanently added 'ec2-52-39-228-214.us-west-2.compute.amazonaws.com,52.39.228.214' (ECDSA) to the list of known hosts.
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(174) [sender=3.1.0]
Traceback (most recent call last):
  File "./spark_ec2.py", line 1528, in <module>
    main()
  File "./spark_ec2.py", line 1520, in main
    real_main()
  File "./spark_ec2.py", line 1356, in real_main
    setup_cluster(conn, master_nodes, slave_nodes, opts, True)
  File "./spark_ec2.py", line 844, in setup_cluster
    modules=modules
  File "./spark_ec2.py", line 1119, in deploy_files
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rsync', '-rv', '-e', 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key_spark_oregon.pem', '/tmp/tmpmC48WQ/', u'root@ec2-52-39-228-214.us-west-2.compute.amazonaws.com:/']' returned non-zero exit status 2

Why do I get this error? Is there somebody who could help me on this? Thanks a lot.

**Comment by nchammas** [comment]
spark-ec2 does not support launching clusters running Ubuntu. It's built to work with custom Amazon Linux AMIs that expect you to log in as `root` and that have specific versions of Unix utilities which may not exist on other distributions.

**Comment by yj-yjh-yj** [comment]
@nchammas Thanks a lot for your reply!
