### ISSUE TITLE
Hive context

### ISSUE THREAD

**Issue by jamborta** [amplab/spark-ec2#28]
Hi,

I have created a cluster using branch-1.6, when I try to create a HiveContext I get:

("You must build Spark with Hive. Export 'SPARK_HIVE=true' and run build/sbt assembly", Py4JJavaError(u'An error occurred while calling None.org.apache.spark.sql.hive.HiveContext.\n', JavaObject id=o332))

would it be possible to user a spark jar where Hive is enabled?

**Comment by shivaram** [comment]
Right now we just use binary distributions provided by the Spark project (i.e. from http://spark.apache.org/downloads.html). You can open a Spark JIRA to see if other builds i.e. with Hive can be supported there.
