### ISSUE TITLE
set temp dir on workers (SPARK_WORKER_DIR)

### ISSUE THREAD

**Issue by jamborta** [amplab/spark-ec2#30]
Hi,

I am running spark 1.6 with an extra disk attached (--ebs-vol-size), trying to make spark workers to write to that disk. Seems spark has the option SPARK_WORKER_DIR, that would do that, but it does not seem to pick it up in this setting (I set it in /root/spark/conf/spark-env.sh). Is there a way to achieve this?

(SPARK_LOCAL_DIRS works on the master node though)

**Comment by shivaram** [comment]
You might need to copy `spark-env.sh` to all the workers using `/root/spark-ec2/copy-dir` and then restart Spark.

**Comment by jamborta** [comment]
@shivaram thanks, that worked.
