### ISSUE TITLE
spark-ec2 scripts with spark-2.0.0-preview

### ISSUE THREAD

**Issue by codeexplorer** [amplab/spark-ec2#33]
spark-2.0.0-preview doesnt have spark-ec2 scripts shipped with it.
I tried tweaking the spark-ec2 scripts from older releases to accomodate spark-2.0.0-preview but couldnt get those to work.

Here's the relevant email thread from the user/dev mailing lists:

Shivaram Venkataraman shivaram@eecs.berkeley.edu via spark.apache.org 
1:06 PM (16 minutes ago)

Can you open an issue on https://github.com/amplab/spark-ec2 ?  I
think we should be able to escape the version string and pass the
2.0.0-preview through the scripts

Shivaram

On Tue, Jun 14, 2016 at 12:07 PM, Sunil Kumar
parvat_2000@yahoo.com.invalid wrote:

> Hi,
> 
> The spark-ec2 scripts are missing from spark-2.0.0-preview. Is there a
> workaround available ? I tried to change the ec2 scripts to accomodate
> spark-2.0.0...If I call the release spark-2.0.0-preview, then it barfs
> because the command line argument : --spark-version=spark-2.0.0-preview
> gets translated to spark-2.0.0-preiew (-v is taken as a switch)...If I call
> the release spark-2.0.0, then it cant find it in aws, since it looks for
> http://s3.amazonaws.com/spark-related-packages/spark-2.0.0-bin-hadoop2.4.tgz
> instead of
> http://s3.amazonaws.com/spark-related-packages/spark-2.0.0-preview-bin-hadoop2.4.tgz
> 
> Any ideas on how to make this work ? How can I tweak/hack the code to look
> for spark-2.0.0-preview in spark-related-packages ?
> 
> thanks

**Comment by shivaram** [comment]
cc @thisisdhaas

**Comment by simplyianm** [comment]
+1

**Comment by nchammas** [comment]
@shivaram - I guess we should close this issue since it was addressed by #35.

**Comment by shivaram** [comment]
Closed by #35
