### ISSUE TITLE
Branch-1.6 missing latest spark stable, and wrong DEFAULT_SPARK_EC2_BRANCH set

### ISSUE THREAD

**Issue by cjosephson** [amplab/spark-ec2#40]
The spark_ec2.py script in branch-1.6 is missing spark versions 1.6.1 and 1.6.2. Furthermore, the DEFAULT_SPARK_EC2_BRANCH  is set to branch-1.5 inside the branch-1.6.

I forked the project and fixed the issues I was seeing, and verified it by successfully launching a cluster running 1.6.2.  Then I made a pull request last week (https://github.com/amplab/spark-ec2/pull/37) for the changes I made, but it seems like nobody has looked at it yet. It would be great to either have that merged or some other fix to be committed so users can run the latest stable version of spark on EC2 clusters.

**Comment by shivaram** [comment]
Thanks @cjosephson -- I'll take a look at the PR today

**Comment by shivaram** [comment]
Closed by #37
