### ISSUE TITLE
Exception: pyspark does not support any application options

### ISSUE THREAD

**Issue by yicunqian** [amplab/spark-ec2#44]
So I launched an ec2 cluster via spark-ec2 and it worked well, until when I tried to launch an iPython session, the error came out as: "Exception in thread "main" java.lang.IllegalArgumentException: pyspark does not support any application options." Actually the same launch command worked just a few days ago and it fails now. Any solutions for that? Thanks.

**Comment by shivaram** [comment]
I dont think this is an issue with the ec2 scripts and this might be a better question for the spark user mailing list

**Comment by yicunqian** [comment]
True. But I would appreciate any help even if it's not typically relevant to the ec2 script. Thank you anyway.

**Comment by AEDWIP** [comment]
Hi Yicun

Very strange. I use the spark-ec2 script in spark 1.6.1. I upgrade to
python3

I launch my notebook sever as follows. I have never seen your problem before

$ cat startIPythonNotebook.sh

export PYSPARK_PYTHON=python3.4

export PYSPARK_DRIVER_PYTHON=python3.4

export IPYTHON_OPTS="notebook --no-browser --port=7000 --log-level=WARN"

if [ -z "$MASTER_URL" ]; then

```
    echo "ERROR: MASTER_URL is not set.
```

echo base url should be something like
'spark://ec2-54-214-211-122.us-west-1.compute.amazonaws.com'"

#echo use port 7077 for client mode

#echo use port 6066 for cluster mode

```
    exit 1
```

Fi

# extra packages we need to add to all the works

# https://github.com/databricks/spark-csv

# packages are ',' seperate with no white space

extraPkgs="--packages
com.databricks:spark-csv_2.10:1.4.0,datastax:spark-cassandra-connector:1.6.0
-M1-s_2.10"

#

# allow notebooks to use all avalible resources

# 

$SPARK_ROOT/bin/pyspark \

```
--master $MASTER_URL \

--driver-memory 2G \

--executor-memory 6G \

$extraPkgs \

$*
```

From:  Yicun Qian notifications@github.com
Reply-To:  amplab/spark-ec2
<reply+00725a2f900511bd3d65b6e4a0d9ed9024432c9862b06b8692cf0000000113b879359
2a169ce0a115cf3@reply.github.com>
Date:  Tuesday, August 2, 2016 at 8:07 AM
To:  amplab/spark-ec2 spark-ec2@noreply.github.com
Subject:  [amplab/spark-ec2] Exception: pyspark does not support any
application options (#44)
