### ISSUE TITLE
Fingerprint check 

### ISSUE THREAD

**Issue by jgustave** [amplab/spark-ec2#50]
Hello, I'm trying out your tool on 2.0-branch using osx 10.10.5

The machines are created in EC2, but then the script is unable to proceed with the rest of the provisioning. (I get the below error repeatedly). 
However if I manually ssh in to the machines the script unblocks and proceeds. If I had to guess I would say it's related to the prompt for authenticity/fingerprint check.

---

Warning: SSH connection error. (This could be temporary.)
Host: ec2-54-69-107-29.us-west-2.compute.amazonaws.com
SSH return code: 255
SSH output: ssh: connect to host ec2-54-69-107-29.us-west-2.compute.amazonaws.com port 22: Connection refused

**Comment by shivaram** [comment]
It usually takes some time for the hosts to be ssh ready. If you run into this issue you can restart the script with `--resume` and it will try to reconnect to the already launched hosts.

FWIW we already skip host key checking in https://github.com/amplab/spark-ec2/blob/dcdc566b9e243a5be1362e8944f0ec16db3a7ea9/spark_ec2.py#L1151

**Comment by jgustave** [comment]
Ok, thanks. And thanks for this set of scripts.
