### ISSUE TITLE
Making a node running spark-ec2 the master node

### ISSUE THREAD

**Issue by c4goldsw** [amplab/spark-ec2#63]
The title pretty much says everything.  I want to be able to use spark-ec2 to (in a single command):
1. Create a set of slaves
2. Launch Spark on the node spark-ec2 is running on
3. Launch Spark on the slaves
4. Register each slave with the master

If this already isn't implemented (I've seen taken a quick glance through the source and it doesn't seem like it is), I'll probably go about doing it myself.

[It seems like this is a good place to start](https://github.com/amplab/spark-ec2/blob/branch-1.6/spark_ec2.py#L702) (line 702 of spark_ec2.py, in launch()).

``` python
# Launch or resume masters
if existing_masters:
    print("Starting master...")
    for inst in existing_masters:
        if inst.state not in ["shutting-down", "terminated"]:
            inst.start()
    master_nodes = existing_masters
```

Ideally, all I'd have to do is supply the current node as a master, then leave the rest of the script in it's current state.  Further modifications could be made when stopping the cluster (i.e. ensuring we don't also stop the master).  @hyviquel and @rxin , how does this sound?

**Comment by shivaram** [comment]
Yeah there is a flag `--use-existing-master` that tries to lookup the master machine by the instance tag.  However running spark_ec2.py from the master node isn't a use case that we probably intend to support. A lot of the logic involves ssh'ing to master, slaves and it might be too much work to remove that etc. Is there a specific use case where running spark_ec2.py inside the cluster is required ?

**Comment by c4goldsw** [comment]
I'm going to be working with a dataset that's over 100 GB in size, and rather than having to transfer that data between S3 and my master node, I'd rather just launch the master from an AMI (with the data on it).  I'll probably go about implementing this myself.

**Comment by shivaram** [comment]
Theres a few of ways to handle this:
- you can put the data in a EBS volume and once the spark cluster comes up you can attach that ebs volume to just the master node
- if your data is a AMI and you don't mind using that for all the nodes you can just launch spark-ec2 with that ami-id
- finally depending on your processing needs, you can also just use Spark to read from S3 and not make a copy to the single node. 

Anyways this isn't spark-ec2 specific, so `user@spark.apache.org` is probably a better place to get more discussion on this.

**Comment by c4goldsw** [comment]
Hey, thanks for the reply.  I'll just go with the first option.  Thanks!
