### ISSUE TITLE
Need support for ca-central-1

### ISSUE THREAD

**Issue by bfleming-ciena** [amplab/spark-ec2#99]
Need the new boto dist included > 2.44 that supports canada.

Could someone suggest how I change the dist for boto?

**Comment by bfleming-ciena** [comment]
In general, support for the ca-central-1 (canada) region.

**Comment by nchammas** [comment]
As explained in [this comment](https://github.com/amplab/spark-ec2/issues/94#issuecomment-288738362) (and in other discussions on GitHub and the Spark mailing list), new regions are not likely to be added to spark-ec2.

**Comment by bfleming-ciena** [comment]
@nchammas Thank you very much for pointing me to that.
